Add :max_redirects option
ruby/open-uri pull request #18
Opened 2023-01-14 04:32 UTC by ankane

Adds an option to limit the number of redirects.

```ruby
URI.open(url, max_redirects: 2)
```

There's no limit by default for backward compatibility, but I think it'd be good for include one in a future version.

2023-11-09 15:30 UTC, jeremyevans requested changes
Thanks for working on this.  I like this idea, I just have a couple of requested changes.

2023-11-09 15:30 UTC, jeremyevans commented on lib/open-uri.rb
> +    :max_redirects => nil,
I think we should set a maximum number of redirects by default to avoid infinite redirect loops.  Maybe 64?

2023-11-09 15:30 UTC, jeremyevans commented on lib/open-uri.rb
> +        raise "Too many redirects" if max_redirects && uri_set.size > max_redirects
We probably should have a specific exception class for this, so users that want to catch this don't have to rescue RuntimeError.

2023-11-09 23:25 UTC, ankane commented
Thanks @jeremyevans, updated based on the feedback.

2023-11-10 06:10 UTC, jeremyevans approved these changes

2023-12-07 07:00 UTC, merged